"use client";
import { useState } from 'react';
import { Newspaper, Calendar, Sparkles, ExternalLink, Clock } from 'lucide-react';

interface NewsItem {
    id: string;
    title: string;
    summary: string;
    source: string;
    timestamp: Date;
    sentiment: 'bullish' | 'bearish' | 'neutral';
}

// Demo news data
const demoNews: NewsItem[] = [
    {
        id: '1',
        title: 'Fed Signals Potential Rate Cuts in 2025',
        summary: 'Federal Reserve officials indicate a shift in monetary policy stance, with multiple rate cuts expected in the coming year.',
        source: 'Reuters',
        timestamp: new Date(),
        sentiment: 'bullish'
    },
    {
        id: '2',
        title: 'Bitcoin ETFs See Record Inflows',
        summary: 'Institutional demand continues to surge as spot Bitcoin ETFs record $1.2B in daily inflows, the highest since launch.',
        source: 'Bloomberg',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
        sentiment: 'bullish'
    },
    {
        id: '3',
        title: 'Tech Earnings Beat Expectations',
        summary: 'Major tech companies report stronger than expected Q4 earnings, driving Nasdaq to new highs.',
        source: 'CNBC',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
        sentiment: 'bullish'
    }
];

function NewsCard({ item }: { item: NewsItem }) {
    const sentimentColors = {
        bullish: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
        bearish: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
        neutral: 'bg-white/[0.04] text-white/40 border-white/[0.06]'
    };

    const formatTime = (date: Date) => {
        const now = new Date();
        const diff = Math.floor((now.getTime() - date.getTime()) / 1000 / 60);
        if (diff < 60) return `${diff}m ago`;
        return `${Math.floor(diff / 60)}h ago`;
    };

    return (
        <article className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-5 hover:border-white/10 transition-all group">
            <div className="flex items-start justify-between gap-4 mb-3">
                <h3 className="text-[15px] font-medium text-white/90 leading-tight group-hover:text-white transition-colors">
                    {item.title}
                </h3>
                <span className={`px-2 py-0.5 rounded text-[10px] font-medium uppercase border ${sentimentColors[item.sentiment]}`}>
                    {item.sentiment}
                </span>
            </div>

            <p className="text-[13px] text-white/50 leading-relaxed mb-4">
                {item.summary}
            </p>

            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4 text-[12px] text-white/30">
                    <span className="flex items-center gap-1">
                        <ExternalLink size={12} />
                        {item.source}
                    </span>
                    <span className="flex items-center gap-1">
                        <Clock size={12} />
                        {formatTime(item.timestamp)}
                    </span>
                </div>
            </div>
        </article>
    );
}

// AI Daily Briefing Component
function DailyBriefing() {
    return (
        <div className="bg-gradient-to-br from-purple-500/10 to-blue-500/10 border border-purple-500/20 rounded-xl p-6 mb-8">
            <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-lg bg-purple-500/20 flex items-center justify-center">
                    <Sparkles size={16} className="text-purple-400" />
                </div>
                <div>
                    <h2 className="text-[15px] font-semibold text-white">AI Daily Briefing</h2>
                    <p className="text-[12px] text-white/40">Generated by Gemini Flash</p>
                </div>
            </div>

            <div className="prose prose-invert prose-sm max-w-none">
                <p className="text-[14px] text-white/70 leading-relaxed">
                    🌅 <strong>Good morning, Trader!</strong> Markets are showing signs of bullish momentum
                    with the S&P 500 futures up 0.4% pre-market. Key focus today: Fed minutes release
                    at 2PM EST and ongoing earnings season. Bitcoin holding above $68K support with
                    institutional flows remaining positive.
                </p>
                <p className="text-[14px] text-white/70 leading-relaxed mt-3">
                    🎯 <strong>Today&apos;s Bias:</strong> <span className="text-emerald-400">BULLISH</span> —
                    Risk-on sentiment prevails, but watch for volatility around Fed announcement.
                </p>
            </div>
        </div>
    );
}

export default function NewsHubPage() {
    const [news] = useState<NewsItem[]>(demoNews);

    return (
        <div className="min-h-screen bg-[#09090b]">
            {/* Header */}
            <header className="h-14 border-b border-white/[0.06] flex items-center justify-between px-6">
                <div className="flex items-center gap-3">
                    <Newspaper size={20} className="text-[#00F0FF]" />
                    <div>
                        <h1 className="text-[15px] font-semibold text-white">News Hub</h1>
                        <p className="text-[12px] text-white/40">AI-curated market intelligence</p>
                    </div>
                </div>
                <div className="flex items-center gap-2 text-[12px] text-white/40">
                    <Calendar size={14} />
                    <span>{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })}</span>
                </div>
            </header>

            {/* Main Content */}
            <main className="p-6 max-w-4xl mx-auto">
                {/* AI Daily Briefing */}
                <DailyBriefing />

                {/* News Feed */}
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                        <h2 className="text-[13px] font-medium text-white/40 uppercase tracking-wider">
                            Latest Headlines
                        </h2>
                        <button className="text-[12px] text-white/30 hover:text-white/50 transition-colors">
                            Refresh
                        </button>
                    </div>

                    <div className="space-y-3">
                        {news.map(item => (
                            <NewsCard key={item.id} item={item} />
                        ))}
                    </div>
                </div>
            </main>
        </div>
    );
}
